//170521
export const objData = {
  SET_OBJ_CURRENT_FOR_OBJ_CARD_PAGE: 'SET_OBJ_CURRENT_FOR_OBJ_CARD_PAGE', //   for User Card Page 050521
  SET_FILTER_SENDER_FOR_OBJ_CARD_PAGE: 'SET_FILTER_SENDER_FOR_OBJ_CARD_PAGE', //   for User Card Page 050521
  SET_FILTER_OWN_FOR_OBJ_CARD_PAGE: 'SET_FILTER_OWN_FOR_OBJ_CARD_PAGE', //   for User Card Page 050521
  SET_FILTER_DATE_START_FOR_OBJ_CARD_PAGE: 'SET_FILTER_DATE_START_FOR_OBJ_CARD_PAGE', //   for User Card Page 050521
  SET_FILTER_DATE_END_FOR_OBJ_CARD_PAGE: 'SET_FILTER_DATE_END_FOR_OBJ_CARD_PAGE', //   for User Card Page 050521
};

