//170521
export const objData = {
  ERROR_FETCH_OBJS_DATA_FOR_OBJS_PAGE: 'ERROR_FETCH_OBJS_DATA_FOR_OBJS_PAGE', //   for User Card Page 050521
  SET_OBJ_CURRENT_FOR_OBJ_CARD_PAGE: 'SET_OBJ_CURRENT_FOR_OBJ_CARD_PAGE', //   for User Card Page 050521
  SET_FILTER_SENDER_FOR_OBJ_CARD_PAGE: 'SET_FILTER_SENDER_FOR_OBJ_CARD_PAGE', //   for User Card Page 050521
  SET_FILTER_OWN_FOR_OBJ_CARD_PAGE: 'SET_FILTER_OWN_FOR_OBJ_CARD_PAGE', //   for User Card Page 050521
  SET_FILTER_DATE_START_FOR_OBJ_CARD_PAGE: 'SET_FILTER_DATE_START_FOR_OBJ_CARD_PAGE', //   for User Card Page 050521
  SET_FILTER_DATE_END_FOR_OBJ_CARD_PAGE: 'SET_FILTER_DATE_END_FOR_OBJ_CARD_PAGE', //   for User Card Page 050521
};

//210521
export const objFilter = {
  SET_FILTER_FIELD_OBJS_FOR_OBJS_PAGE: 'SET_FILTER_FIELD_OBJS_FOR_OBJS_PAGE', //   for OBJ Page 210521
  SET_FILTER_FIELD_ORGS_FOR_OBJS_PAGE: 'SET_FILTER_FIELD_ORGS_FOR_OBJS_PAGE', //   for OBJ Page 210521
  SET_FILTER_SELECTOR_BENEFICE_FOR_OBJS_PAGE: 'SET_FILTER_SELECTOR_BENEFICE_FOR_OBJS_PAGE', //   for OBJ Page 210521
  SET_FILTER_SELECTOR_STATUS_FOR_OBJS_PAGE: 'SET_FILTER_SELECTOR_STATUS_FOR_OBJS_PAGE', //   for OBJ Page 210521
  SET_FILTER_SELECTOR_TYPE_FOR_OBJS_PAGE: 'SET_FILTER_SELECTOR_TYPE_FOR_OBJS_PAGE', //   for OBJ Page 210521
  SET_FILTER_DATE_START_OBJS_PAGE: 'SET_FILTER_DATE_START_OBJS_PAGE', //   for OBJ Page 210521
  SET_FILTER_DATE_END_OBJS_PAGE: 'SET_FILTER_DATE_END_OBJS_PAGE', //   for OBJ Page 210521
};

