export const ADD_ORGANIZATION = 'ADD_ORGANIZATION';
export const ADD_POINT = 'ADD_POINT';

// export const FETCH_USERS_START = 'FETCH_USERS_START';
// export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
// export const FETCH_USERS_FAILURE = 'FETCH_USERS_FAILURE';
// export const FETCH_COUNT_OBJ_START = 'FETCH_COUNT_OBJ_START';