// for login
export const UserActionTypes = {
  SET_CURRENT_USER: 'SET_CURRENT_USER',
  
};

//050521
export const userData = {
  SET_USER_SHORT_CUR_FOR_USER_CARD_PAGE: 'SET_USER_SHORT_CUR_FOR_USER_CARD_PAGE', //   for User Card Page 050521
  SET_USER_CURRENT_FOR_USER_CARD_PAGE: 'SET_USER_CURRENT_FOR_USER_CARD_PAGE', //   for User Card Page 050521
  FETCH_USER_CURRENT_FOR_USER_CARD_DETAILS_PAGE: 'FETCH_USER_CURRENT_FOR_USER_CARD_DETAILS_PAGE', //   for User Card Page 050521
  FETCH_USER_STATS_FOR_USER_CARD_DETAILS_PAGE: 'FETCH_USER_STATS_FOR_USER_CARD_DETAILS_PAGE', //   for User Card Page 050521
};
