// for login
export const UserActionTypes = {
  SET_CURRENT_USER: 'SET_CURRENT_USER',
  
};

//050521
export const userData = {
  SET_USER_SHORT_CUR_FOR_USER_CARD_PAGE: 'SET_USER_SHORT_CUR_FOR_USER_CARD_PAGE', //   for User Card Page 050521
  SET_USER_CURRENT_FOR_USER_CARD_PAGE: 'SET_USER_CURRENT_FOR_USER_CARD_PAGE', //   for User Card Page 050521
  ERROR_FETCH_USER_DATA_CUR_FOR_USER_DETAILS_PAGE: 'ERROR_FETCH_USER_DATA_CUR_FOR_USER_DETAILS_PAGE', //   for User Card Page FOR curUserStatsData 210521
  FETCH_USER_CURRENT_FOR_USER_CARD_DETAILS_PAGE: 'FETCH_USER_CURRENT_FOR_USER_CARD_DETAILS_PAGE', //   for User Card Page 050521
  FETCH_USER_STATS_FOR_USER_CARD_DETAILS_PAGE: 'FETCH_USER_STATS_FOR_USER_CARD_DETAILS_PAGE', //   for User Card Page 050521
  FILTER_USER_FIELD_FOR_USER_ACTIVE_CARD_DETAILS_PAGE: 'FILTER_USER_FIELD_FOR_USER_ACTIVE_CARD_DETAILS_PAGE', //   for User Card Page FOR curUserStatsData
  FILTER_USER_DATE_START_FOR_USER_ACTIVE_CARD_DETAILS_PAGE: 'FILTER_USER_DATE_START_FOR_USER_ACTIVE_CARD_DETAILS_PAGE', //   for User Card Page FOR curUserStatsData
  FILTER_USER_DATE_END_FOR_USER_ACTIVE_CARD_DETAILS_PAGE: 'FILTER_USER_DATE_END_FOR_USER_ACTIVE_CARD_DETAILS_PAGE', //   for User Card Page FOR curUserStatsData
  FILTER_USER_REC_TYPE_FOR_USER_ACTIVE_CARD_DETAILS_PAGE: 'FILTER_USER_REC_TYPE_FOR_USER_ACTIVE_CARD_DETAILS_PAGE', //   for User Card Page FOR curUserStatsData
};
